spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

jira:
  url: "https://faang-school.atlassian.net"
  user: "eternity_cr9p@mail.ru"
  token: "ATATT3xFfGF0g9dIKirc2arHnnZUeAE5sBrNTLEk-G5Qj4sv_IrGGOoagB3OV2Vp74blkWft_c9cOwk9NjH1FaQYfNE-Rb52JzdVXAhwgahjZ95fq-eAXuh3LW78lpN0vF0EAGgMuZqJcP95CB3YqtHtwrZhCF_BODsZOIUnXBncGDMxkv1HlJA=35702E16"

server:
  port: 8082

logging:
  level:
    root: info

calculations_messages_processing:
  enabled: true

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: projectbucket
    isMocked: false
  payment-service:
    host: http://localhost
    port: 9080
  user-service:
    host: http://localhost
    port: 8080