name: CI

on:
  pull_request:
    branches:
      - kraken-master-stream8

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Clean with Gradle
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run Jacoco Test Coverage Verification
        run: ./gradlew jacocoTestCoverageVerification
