name: CI for projectService

on:
  pull_request:
    branches:
      - hippogriff-master-stream8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}

      - name: Run Tests
        run: ./gradlew clean test

      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Validate Coverage
        run: ./gradlew jacocoTestCoverageVerification

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test