name: CI

on:
  pull_request:
    branches:
      - chimera-master-stream8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon --continue

      - name: Run Tests
        run: ./gradlew test --no-daemon