name: CI

on:
  pull_request:
    branches:
      - kraken-master-stream8

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Run Jacoco Test Coverage Verification
        run: ./gradlew jacocoTestCoverageVerification --no-daemon
