name: CI

on:
  pull_request:
    branches:
      - chimera-master-stream8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run Checkstyle
        run: |
          java -jar config/checkstyle.jar -c config/checkstyle/checkstyle.xml src/main/java

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
